## Retrieve red links considering oldest reference pages (among main pages and redirections)

In [17]:
import pandas as pd
from mw import Timestamp

In [3]:
# get a table only with red links
df_red = pd.read_csv('../working_files/'+'df_red_less_unique.csv', sep='^')

In [4]:
# check (manually with web.archive.org) whether this method of retrieving red links is OK.
parent_page = 'Мільярд'

temp_df = df_red.loc[df_red['parent_page'] == parent_page]

sorted_temp_df = temp_df.sort_values(by='rvtimestamp')

print('title: ', parent_page)

print('number of red links: ', sorted_temp_df.shape[0])

print('number of unique values: ', len(sorted_temp_df.link_title.unique()))

title:  Мільярд
number of red links:  17
number of unique values:  5

In [5]:
timestamp = Timestamp('2011-08-15T20:06:13Z')
sorted_temp_df.loc[df_red['rvtimestamp'] == timestamp]

Empty DataFrame
Columns: [parent_page, rvtimestamp, link_title, link_status]
Index: []

In [6]:
sorted_temp_df[sorted_temp_df['link_title']=='суперечка']

Empty DataFrame
Columns: [parent_page, rvtimestamp, link_title, link_status]
Index: []

In [69]:
df_blue = df_red = pd.read_csv('../working_files/'+'df_blue_less_unique.csv', sep='^')

df_blue_temp = df_blue.loc[df_blue['parent_page'] == parent_page]

df_blue_temp.loc[df_blue['rvtimestamp'] == timestamp]

## Results

In [7]:
exp3_result_df = pd.read_excel('/media/andrii/earth/Katia/CS/!redlinks_project/red-links-v2.0/'+'exp3_analysis.xlsx')

In [8]:
exp3_result_df

,parent_page,rv_timestamp,webarchive_timestamp,link_title,real_status,infer_status,result (if check is red),comments,link,main_page_title,Unnamed: 10
0,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Хвильова_модель,red,check,TP,NaN,NaN,NaN,NaN
1,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Орбіталь_електрону,red,check,TP,NaN,NaN,NaN,NaN
2,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Електрон,blue,red,FP,deleted,NaN,NaN,NaN
3,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Атомне_ядро,red,blue,FN,NaN,NaN,NaN,NaN
4,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Настільний_теніс,red,red,TP,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
96,Мова,Timestamp('2011-07-14T18:38:02Z'),Timestamp('2011-07-22T00:00:00Z'),Прохання,red,check,TP,NaN,NaN,NaN,NaN
97,Мова,Timestamp('2011-07-14T18:38:02Z'),Timestamp('2011-07-22T00:00:00Z'),Спонукання,red,check,TP,NaN,NaN,NaN,NaN
98,Мова,Timestamp('2011-07-14T18:38:02Z'),Timestamp('2011-07-22T00:00:00Z'),Теорії_мовлення,red,check,TP,NaN,NaN,NaN,NaN
99,Мова,Timestamp('2011-07-14T18:38:02Z'),Timestamp('2011-07-22T00:00:00Z'),Переконання,blue,red,FP,NaN,NaN,NaN,NaN
100,Мова,Timestamp('2011-07-14T18:38:02Z'),Timestamp('2011-07-22T00:00:00Z'),Список_загрожених_мов,red,check,TP,NaN,NaN,NaN,NaN

In [14]:
print('links correctly marked red: ',
    len(exp3_result_df[exp3_result_df['result (if check is red)'] == 'TP'])/exp3_result_df.shape[0])

links correctly marked red:  0.7821782178217822

In [15]:
fp_res_df = exp3_result_df[exp3_result_df['result (if check is red)'] == 'FP']
print('links incorrectly marked red: ', fp_res_df.shape[0])
fp_res_df

links incorrectly marked red:  12

,parent_page,rv_timestamp,webarchive_timestamp,link_title,real_status,infer_status,result (if check is red),comments,link,main_page_title,Unnamed: 10
2,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Електрон,blue,red,FP,deleted,NaN,NaN,NaN
23,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Левкіпп_(філософ),blue,red,FP,deleted,NaN,NaN,NaN
37,Ядро,Timestamp('2006-05-31T17:57:20Z'),Timestamp('2006-06-24T00:00:00Z'),Ядро_(атома),blue,check,FP,deleted,NaN,NaN,NaN
38,Ядро,Timestamp('2006-05-31T17:57:20Z'),Timestamp('2006-06-24T00:00:00Z'),Мільйон_,blue,check,FP,deleted,NaN,NaN,NaN
54,Хімія,Timestamp('2014-07-09T17:45:50Z'),Timestamp('2014-07-12T00:00:00Z'),Вода,blue,red,FP,deleted and created,NaN,NaN,NaN
55,Хімія,Timestamp('2014-07-09T17:45:50Z'),Timestamp('2014-07-12T00:00:00Z'),Інертні_гази,blue,red,FP,deleted and created,NaN,NaN,NaN
56,Хімія,Timestamp('2014-07-09T17:45:50Z'),Timestamp('2014-07-12T00:00:00Z'),Маса,blue,red,FP,deleted and created,NaN,NaN,NaN
57,Хімія,Timestamp('2014-07-09T17:45:50Z'),Timestamp('2014-07-12T00:00:00Z'),Алфавітний_список_хімічних_елементів,blue,check,FP,deleted,NaN,NaN,NaN
77,Біологія,Timestamp('2014-07-09T14:54:15Z'),Timestamp('2014-07-12T00:00:00Z'),Геракліт,blue,red,FP,deleted and created,NaN,NaN,NaN
78,Коло,Timestamp('2014-03-10T11:42:20Z'),Timestamp('2014-03-03T00:00:00Z'),Дуга,blue,red,FP,deleted and created,NaN,NaN,NaN
87,Речення,Timestamp('2011-08-31T06:44:03Z'),Timestamp('2011-11-07T00:00:00Z'),Думка,blue,red,FP,deleted and created,NaN,NaN,NaN
99,Мова,Timestamp('2011-07-14T18:38:02Z'),Timestamp('2011-07-22T00:00:00Z'),Переконання,blue,red,FP,NaN,NaN,NaN,NaN

In [16]:
fn_res_df = exp3_result_df[exp3_result_df['result (if check is red)'] == 'FN']
print('links incorrectly marked blue: ', fn_res_df.shape[0])
fn_res_df

links incorrectly marked blue:  10

,parent_page,rv_timestamp,webarchive_timestamp,link_title,real_status,infer_status,result (if check is red),comments,link,main_page_title,Unnamed: 10
3,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Атомне_ядро,red,blue,FN,NaN,NaN,NaN,NaN
15,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Кутовий_момент,red,blue,FN,was not connected. Redirection with this title...,NaN,NaN,NaN
19,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Періодична_таблиця,red,blue,FN,was not connected. Redirection with this title...,NaN,NaN,NaN
25,Атом,Timestamp('2005-08-13T10:47:40Z'),Timestamp('2005-09-02T00:00:00Z'),Резерфорд_Ернест,red,blue,FN,was not connected. Redirection with this title...,NaN,NaN,NaN
31,Географія,Timestamp('2017-07-10T10:33:34Z'),Timestamp('2017-07-12T00:00:00Z'),Smithsonian,red,blue,FN,was not connected. Redirection with this title...,NaN,NaN,NaN
33,Мільярд,Timestamp('2011-08-15T20:06:13Z'),Timestamp('2011-07-25T00:00:00Z'),Км³,red,blue,FN,was not connected. Redirection with this title...,[[км³]],кубічний_кілометр,get redirection!!!
40,Хімія,Timestamp('2014-07-09T17:45:50Z'),Timestamp('2014-07-12T00:00:00Z'),Провідники,red,blue,FN,was not connected. Redirection with this title...,[[провідники|провідники]],провідник,NaN
41,Хімія,Timestamp('2014-07-09T17:45:50Z'),Timestamp('2014-07-12T00:00:00Z'),Дисперсні_системи,red,blue,FN,was not connected. Redirection with this title...,[[дисперсні системи]],дисперсна_система,NaN
49,Хімія,Timestamp('2014-07-09T17:45:50Z'),Timestamp('2014-07-12T00:00:00Z'),Теорія_кислот_та_основ,red,blue,FN,was not connected. Redirection with this title...,[[теорія кислот та основ|теорії кислот та основ]],теорії_кислот_і_основ,NaN
95,Мова,Timestamp('2011-07-14T18:38:02Z'),Timestamp('2011-07-22T00:00:00Z'),Суперечка,red,blue,FN,was not connected. Redirection with this title...,[[суперечка|суперечці]],спір,NaN